### ISSUE TITLE
FlightClub and Goat size pricing issue

### ISSUE THREAD

**Issue by danish111** [druv5319/Sneaks-API#13]
**HI**
I have checked sneaks-api its have following issue missing sizing/prices of **FlightClub and Goat** I think this is because of  they both apply google captcha

**Comment by danish111** [comment]
![sizing-price](https://user-images.githubusercontent.com/10942243/99972600-88fa2e00-2dc0-11eb-880f-62e9966ee1ef.PNG)

**Comment by druv5319** [comment]
Yeah. It works completely fine if you use the API on your own but I believe goat and flight club has IP tagged my API server for the website. I may need to use a proxy.

**Comment by danish111** [comment]
But i have deployed this api it returning only stockx sizing/pricing 
http://167.99.199.181:3000/id/555088-140/prices

**Comment by druv5319** [comment]
Weird, I just uninstalled and installed the API on a local server and it seems to work. Maybe you have requested something too many times to where it reached the API limit of the resell sites. What does the console log look like?

**Comment by sunruoshi** [comment]
Same issue. I think it's because of some API request limit. Nothing in the console log, just missing the data.

**Comment by danish111** [comment]
There is an error about token in consloe log regarding flight club

**Comment by MarqueeGaming** [comment]
Same here @danish111

**Comment by druv5319** [comment]
Which version of the sneaks-api are you guys on?

**Comment by danish111** [comment]
Error: Could not connect to Flight Club while grabbing token '
    at Object.getPrices (D:\react\api-sneak\node_modules\sneaks-api\scrapers\flightclub-scraper.js:81:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by jain-aayush1123** [comment]
Facing the same issue for stadium goods and flight club. attaching the error 
`Error: Could not connect to Stadium Goods while searching '
    at Request.getPriceMap [as _callback] (D:\Projects\Web\noded-tut\node_modules\sneaks-api\scrapers\stadiumgoods-scraper.js:59:35)
    at Request.self.callback (D:\Projects\Web\noded-tut\node_modules\request\request.js:185:22)
    at Request.emit (events.js:376:20)
    at Request.<anonymous> (D:\Projects\Web\noded-tut\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:376:20)
    at IncomingMessage.<anonymous> (D:\Projects\Web\noded-tut\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:482:28)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Error: Could not connect to Flight Club while grabbing token '
    at Object.getPrices (D:\Projects\Web\noded-tut\node_modules\sneaks-api\scrapers\flightclub-scraper.js:81:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
{`
