### ISSUE TITLE
Error 403 Forbidden error when trying to get information from Goat

### ISSUE THREAD

**Issue by aryan-chakrabarti** [druv5319/Sneaks-API#32]
Hi,

I tried to run this API on AWS Lambda and Google Firebase both, but when I am running it I get the following error. I end up not being able to retrieve any information from Goat even though I know that the information is there. However, StockX still works:

Error: Could not connect to Goat while grabbing pictures for 'GY3438' Error: 
    at Object.getPictures (/var/task/node_modules/sneaks-api/scrapers/goat-scraper.js:105:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/var/task/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1648073321821,
    socket: 1648073321822,
    lookup: 1648073321862,
    connect: 1648073321863,
    secureConnect: undefined,
    upload: 1648073321863,
    response: 1648073321922,
    end: 1648073321922,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 40,
      tcp: 1,
      tls: undefined,
      request: 0,
      firstByte: 59,
      download: 0,
      total: 101
    }
  }
}

**Comment by jomtek** [comment]
They have strenghtened their Cloudflare security, one workaround would be to use a library such as cloudscraper as well as private residential proxies
